from typing import List, Dict, Any, Optional
import os
import requests


def _normalize_ollama_openai_base(base_url: Optional[str]) -> str:
    """
    Normalize the Ollama base so that we always end up with the server root,
    e.g. "http://localhost:11434". We DO NOT include /v1 here, because we
    will append it when calling the OpenAI-compatible endpoint.

    Users might pass:
      - "http://localhost:11434"
      - "http://localhost:11434/"
      - "http://localhost:11434/v1"
      - "http://localhost:11434/v1/"

    We turn all of these into: "http://localhost:11434".
    """
    if not base_url:
        base_url = "http://localhost:11434"
    base = base_url.rstrip("/")

    # Strip a trailing /v1 if present
    if base.endswith("/v1"):
        base = base[:-3]
    return base


class ModelClient:
    """
    Model client that can use:
      - 'mock'       : no network, returns a fixed script
      - 'ollama'     : Ollama HTTP API via the OpenAI-compatible endpoint
      - 'openrouter' : hosted models via OpenRouter (e.g. DeepSeek)
    """

    def __init__(
        self,
        backend: str = "mock",            # "mock", "ollama", or "openrouter"
        default_model: str = "deepseek/deepseek-chat",
        base_url: Optional[str] = None,
    ):
        self.backend = backend
        self.default_model = default_model

        self.base_url: Optional[str] = None
        self.api_key: Optional[str] = None

        if backend == "ollama":
            # Normalize to server root, e.g. "http://localhost:11434"
            env_base = os.getenv("OLLAMA_BASE_URL")
            self.base_url = _normalize_ollama_openai_base(base_url or env_base)
        
        
        elif backend == "ollama_cloud":
    # Cloud base URL, can override if needed
            self.base_url = base_url or os.getenv("OLLAMA_CLOUD_BASE_URL", "https://ollama.com/api")
            api_key = os.getenv("OLLAMA_API_KEY")
            if not api_key:
                raise RuntimeError(
            "OLLAMA_API_KEY is not set. "
            "Set it in your environment before using backend='ollama_cloud'."
        )
            self.api_key = api_key


        elif backend == "openrouter":
            # OpenRouter base URL
            self.base_url = (base_url or "https://openrouter.ai/api/v1").rstrip("/")

            api_key = os.getenv("OPENROUTER_API_KEY")
            if not api_key:
                raise RuntimeError(
                    "OPENROUTER_API_KEY is not set. "
                    "Set it in your environment before using backend='openrouter'."
                )
            self.api_key = api_key

        else:
            # mock backend: no base_url needed
            self.base_url = base_url

    def chat(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        tools: Optional[List[Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        """
        Return a dict like {"role": "assistant", "content": "..."}.
        """
        chosen_model = model or self.default_model

        # ---------- MOCK BACKEND ----------
        if self.backend == "mock":
            return {
                "role": "assistant",
                "content": (
                    "# Generated by mock ModelClient\n"
                    "def main():\n"
                    "    print('Hello from the mock main agent system!')\n\n"
                    "if __name__ == '__main__':\n"
                    "    main()\n"
                ),
            }

        # ---------- OLLAMA BACKEND (OpenAI-compatible /v1 endpoint) ----------
        if self.backend == "ollama":
            if not self.base_url:
                raise RuntimeError("Ollama backend requires a base_url.")

            # OpenAI-compatible endpoint:
            #   POST {base_url}/v1/chat/completions
            # See: https://docs.ollama.com/api/openai-compatibility
            completions_url = f"{self.base_url}/v1/chat/completions"

            payload: Dict[str, Any] = {
                "model": chosen_model,
                "messages": messages,
            }

            # Ollama ignores the API key for local usage, but some clients require it.
            # Here we don't send any key; if you later point this at a proxy that
            # expects a key, you can extend this class similarly to the openrouter case.
            resp = requests.post(
                completions_url,
                json=payload,
                timeout=300,
            )
            resp.raise_for_status()
            data = resp.json()

            # OpenAI-style chat completion:
            # { "choices": [ { "message": { "role": "...", "content": "..." } } ], ... }
            choices = data.get("choices") or [{}]
            choice = choices[0] or {}
            msg = choice.get("message") or {}

            return {
                "role": msg.get("role", "assistant"),
                "content": msg.get("content", ""),
            }
        if self.backend == "ollama_cloud":
            if not self.base_url:
                raise RuntimeError("ollama_cloud backend requires a base_url.")
        if not self.api_key:
                raise RuntimeError("ollama_cloud backend requires OLLAMA_API_KEY.")

        url = f"{self.base_url}/chat"  # -> https://ollama.com/api/chat

        payload: Dict[str, Any] = {
            "model": chosen_model,
            "messages": messages,
            "stream": False,
        }

        headers = {
        "Authorization": f"Bearer {self.api_key}",
        "Content-Type": "application/json",
        }

        resp = requests.post(url, json=payload, headers=headers, timeout=300)
        resp.raise_for_status()
        data = resp.json()

    # Response is:
    # { "model": "...", "message": { "role": "assistant", "content": "..." }, "done": true, ... }
        msg = data.get("message") or {}

        return {
        "role": msg.get("role", "assistant"),
        "content": msg.get("content", ""),
        }

        # ---------- OPENROUTER BACKEND ----------
        if self.backend == "openrouter":
            if not self.base_url:
                raise RuntimeError("OpenRouter backend requires a base_url.")
            if not self.api_key:
                raise RuntimeError("OpenRouter backend requires OPENROUTER_API_KEY.")

            headers = {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                # Optional but nice: identify your app
                "HTTP-Referer": "https://example.com/agent-forge",  # change if you want
                "X-Title": "Agent Forge Main Agent",
            }

            payload: Dict[str, Any] = {
                "model": chosen_model,
                "messages": messages,
            }

            resp = requests.post(
                f"{self.base_url}/chat/completions",
                headers=headers,
                json=payload,
                timeout=300,
            )
            resp.raise_for_status()
            data = resp.json()

            choices = data.get("choices") or [{}]
            choice = choices[0] or {}
            msg = choice.get("message") or {}

            return {
                "role": msg.get("role", "assistant"),
                "content": msg.get("content", ""),
            }

        raise ValueError(f"Unknown backend: {self.backend}")
